name: Service CI/CD (buildpacks)

on:
  push:
    branches: [ "main" ]  # 필요시 변경
    paths: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildpack-build:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: .  # 모노레포면 하위 경로 지정 (예: ./apps/frontend)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pack (Buildpacks CLI)
        uses: buildpacks/github-actions/setup-pack@v5.8.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWD }}

      # 서비스명/네임스페이스/이미지 경로를 먼저 셸 변수로 만든 뒤 GITHUB_ENV에 저장
      - name: Set SERVICE_NAME / NAMESPACE / IMAGE_REPO
        run: |
          SERVICE_NAME="${GITHUB_REPOSITORY##*/}"
          NAMESPACE="${{ secrets.DOCKER_NAMESPACE || secrets.DOCKER_ID }}"
          echo "SERVICE_NAME=${SERVICE_NAME}" >> "$GITHUB_ENV"
          echo "NAMESPACE=${NAMESPACE}" >> "$GITHUB_ENV"
          echo "IMAGE_REPO=docker.io/${NAMESPACE}/${SERVICE_NAME}" >> "$GITHUB_ENV"

      - name: Ensure jq is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      # Docker Hub 리포지토리 자동 생성 (PAT 권장)
      - name: Ensure Docker Hub repository exists
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
          REPO: ${{ env.SERVICE_NAME }}
          DH_USER: ${{ secrets.DOCKER_ID }}
          DH_PASS: ${{ secrets.DOCKERHUB_PAT || secrets.DOCKER_PASSWD }}
        run: |
          set -e
          base="https://hub.docker.com/v2"

          # 로그인(JWT 토큰 발급)
          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"username\":\"$DH_USER\",\"password\":\"$DH_PASS\"}" \
            "$base/users/login" | jq -r '.token')

          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Failed to obtain Docker Hub token"; exit 1
          fi

          # 1) 존재 확인
          status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: JWT $TOKEN" \
            "$base/repositories/$NAMESPACE/$REPO/")

          if [ "$status" = "200" ]; then
            echo "Repository exists: $NAMESPACE/$REPO"
            exit 0
          fi
          if [ "$status" != "404" ]; then
            echo "Unexpected status: $status"; exit 1
          fi

          # 2) 생성: 개인/조직 분기
          if [ "$NAMESPACE" = "$DH_USER" ]; then
            create_url="$base/repositories/"
            payload=$(jq -n --arg name "$REPO" --argjson private false '{name:$name, is_private:$private}')
          else
            create_url="$base/repositories/$NAMESPACE/"
            payload=$(jq -n --arg name "$REPO" --argjson private false '{name:$name, is_private:$private}')
          fi

          create_status=$(curl -s -o /tmp/dh_create_resp.json -w "%{http_code}" \
            -H "Authorization: JWT $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload" "$create_url")

          if [ "$create_status" != "201" ] && [ "$create_status" != "200" ]; then
            echo "Create failed: HTTP $create_status"
            cat /tmp/dh_create_resp.json || true
            exit 1
          fi

          echo "Created repository: $NAMESPACE/$REPO"

      - name: Compute tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build & push with pack (sha + latest)
        run: |
          pack version
          pack build "${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.tag }}" \
            --builder paketobuildpacks/builder-jammy-base \
            --path "${{ env.BUILD_PATH }}" \
            --publish \
            --tag "${{ env.IMAGE_REPO }}:latest"
