name: Service CI/CD (buildpacks)

on:
  push:
    branches: [ "main" ]  # 필요시 main 변경
    paths: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildpack-build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: test01
      BUILD_PATH: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWD }}
name: Service CI/CD (buildpacks)

on:
  push:
    branches: [ "main" ]  # 필요시 변경
    paths: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildpack-build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: test01           # ← 실제 서비스명
      BUILD_PATH: .                  # 모노레포면 하위 경로로 변경
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pack (Buildpacks CLI)
        uses: buildpacks/github-actions/setup-pack@v5.8.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Set IMAGE_REPO
        run: echo "IMAGE_REPO=docker.io/${{ secrets.DOCKER_ID }}/${SERVICE_NAME}" >> "$GITHUB_ENV"

      - name: Ensure jq is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Ensure Docker Hub repository exists
        env:
          NAMESPACE: ${{ secrets.DOCKER_ID }}
          REPO: ${{ env.SERVICE_NAME }}
          DH_USER: ${{ secrets.DOCKER_ID }}
          DH_PASS: ${{ secrets.DOCKERHUB_PAT || secrets.DOCKER_PASSWD }}
        run: |
          set -e
          base="https://hub.docker.com/v2"
          status=$(curl -s -o /dev/null -w "%{http_code}" -u "$DH_USER:$DH_PASS" \
            "$base/repositories/$NAMESPACE/$REPO/")
          if [ "$status" = "200" ]; then
            echo "Repository exists: $NAMESPACE/$REPO"
            exit 0
          fi
          if [ "$status" != "404" ]; then
            echo "Unexpected status: $status"; exit 1
          fi
          payload=$(jq -n --arg ns "$NAMESPACE" --arg name "$REPO" --argjson private false \
            '{namespace:$ns, name:$name, is_private:$private}')
          curl -s -f -u "$DH_USER:$DH_PASS" -H "Content-Type: application/json" \
            -d "$payload" "$base/repositories/" > /dev/null
          echo "Created repository: $NAMESPACE/$REPO"

      - name: Compute tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build & push with pack (sha + latest)
        run: |
          pack version
          pack build "${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.tag }}" \
            --builder paketobuildpacks/builder-jammy-base \
            --path "${{ env.BUILD_PATH }}" \
            --publish \
            --tag "${{ env.IMAGE_REPO }}:latest"
      - name: Set IMAGE_REPO
        run: echo "IMAGE_REPO=docker.io/${{ secrets.DOCKER_ID }}/${SERVICE_NAME}" >> "$GITHUB_ENV"

      - name: Compute tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build with pack (Paketo builder)
        uses: buildpacks/github-actions/setup-pack@v5.8.1
        with:
          args: >
            build ${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.tag }}
            --builder paketobuildpacks/builder-jammy-base
            --path ${{ env.BUILD_PATH }}
            --publish

      - name: Tag latest
        run: |
          docker pull ${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.tag }}
          docker tag  ${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.tag }} ${{ env.IMAGE_REPO }}:latest
          docker push ${{ env.IMAGE_REPO }}:latest
